[package]
name = "ansi-img"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
term_size = "0.3.2"
ctrlc = "3.4.4"
clap = { version = "4.5.4", features = ["derive"] }
libc = "0.2.155"
